### ISSUE TITLE
Problem with "getusername:quit"

### ISSUE THREAD

**Issue by braimee** [SpiderLabs/Spray#1]
Hi there,

I have a fresh Kali box and was trying to run Spray against a new lab AD environment.  Even though I knew I had a good username and password list, Spray would never find a match on its login attempts.  I went through the `rpcclient` commands manually and I think the issue is this:

`getusername:quit` should be `getusername;quit`

Once I made that change throughout the script, everything ran fine for me!

Thanks,
Brian

**Comment by Green-Wolf** [comment]
Hey braimee, thanks for pointing that out, i'll get the fix merged in. I'm glad you got it working though, good debugging skills! This reminded me to merge in the new cisco web vpn spraying module too!
